# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ops_history_api import OpsHistoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOpsHistoryApi(unittest.TestCase):
    """OpsHistoryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ops_history_api.OpsHistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ops_v1_history_create(self):
        """Test case for ops_v1_history_create

        """
        pass

    def test_ops_v1_history_delete(self):
        """Test case for ops_v1_history_delete

        """
        pass

    def test_ops_v1_history_list(self):
        """Test case for ops_v1_history_list

        """
        pass

    def test_ops_v1_history_partial_update(self):
        """Test case for ops_v1_history_partial_update

        """
        pass

    def test_ops_v1_history_read(self):
        """Test case for ops_v1_history_read

        """
        pass

    def test_ops_v1_history_update(self):
        """Test case for ops_v1_history_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
