# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ops_command_executions_api import OpsCommandExecutionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOpsCommandExecutionsApi(unittest.TestCase):
    """OpsCommandExecutionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ops_command_executions_api.OpsCommandExecutionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ops_v1_command_executions_create(self):
        """Test case for ops_v1_command_executions_create

        """
        pass

    def test_ops_v1_command_executions_delete(self):
        """Test case for ops_v1_command_executions_delete

        """
        pass

    def test_ops_v1_command_executions_list(self):
        """Test case for ops_v1_command_executions_list

        """
        pass

    def test_ops_v1_command_executions_partial_update(self):
        """Test case for ops_v1_command_executions_partial_update

        """
        pass

    def test_ops_v1_command_executions_read(self):
        """Test case for ops_v1_command_executions_read

        """
        pass

    def test_ops_v1_command_executions_update(self):
        """Test case for ops_v1_command_executions_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
