# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.perms_user_groups_api import PermsUserGroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPermsUserGroupsApi(unittest.TestCase):
    """PermsUserGroupsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.perms_user_groups_api.PermsUserGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perms_v1_user_groups_assets_list(self):
        """Test case for perms_v1_user_groups_assets_list

        """
        pass

    def test_perms_v1_user_groups_nodes_assets_list(self):
        """Test case for perms_v1_user_groups_nodes_assets_list

        """
        pass

    def test_perms_v1_user_groups_nodes_assets_list_0(self):
        """Test case for perms_v1_user_groups_nodes_assets_list_0

        """
        pass

    def test_perms_v1_user_groups_nodes_assets_tree_list(self):
        """Test case for perms_v1_user_groups_nodes_assets_tree_list

        """
        pass

    def test_perms_v1_user_groups_nodes_list(self):
        """Test case for perms_v1_user_groups_nodes_list

        """
        pass

    def test_perms_v1_user_groups_nodes_tree_list(self):
        """Test case for perms_v1_user_groups_nodes_tree_list

        """
        pass

    def test_perms_v1_user_groups_remote_apps_list(self):
        """Test case for perms_v1_user_groups_remote_apps_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
