# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orgs_orgs_api import OrgsOrgsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgsOrgsApi(unittest.TestCase):
    """OrgsOrgsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.orgs_orgs_api.OrgsOrgsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orgs_v1_orgs_create(self):
        """Test case for orgs_v1_orgs_create

        """
        pass

    def test_orgs_v1_orgs_delete(self):
        """Test case for orgs_v1_orgs_delete

        """
        pass

    def test_orgs_v1_orgs_list(self):
        """Test case for orgs_v1_orgs_list

        """
        pass

    def test_orgs_v1_orgs_membership_admins_create(self):
        """Test case for orgs_v1_orgs_membership_admins_create

        """
        pass

    def test_orgs_v1_orgs_membership_admins_delete(self):
        """Test case for orgs_v1_orgs_membership_admins_delete

        """
        pass

    def test_orgs_v1_orgs_membership_admins_list(self):
        """Test case for orgs_v1_orgs_membership_admins_list

        """
        pass

    def test_orgs_v1_orgs_membership_admins_read(self):
        """Test case for orgs_v1_orgs_membership_admins_read

        """
        pass

    def test_orgs_v1_orgs_membership_users_create(self):
        """Test case for orgs_v1_orgs_membership_users_create

        """
        pass

    def test_orgs_v1_orgs_membership_users_delete(self):
        """Test case for orgs_v1_orgs_membership_users_delete

        """
        pass

    def test_orgs_v1_orgs_membership_users_list(self):
        """Test case for orgs_v1_orgs_membership_users_list

        """
        pass

    def test_orgs_v1_orgs_membership_users_read(self):
        """Test case for orgs_v1_orgs_membership_users_read

        """
        pass

    def test_orgs_v1_orgs_partial_update(self):
        """Test case for orgs_v1_orgs_partial_update

        """
        pass

    def test_orgs_v1_orgs_read(self):
        """Test case for orgs_v1_orgs_read

        """
        pass

    def test_orgs_v1_orgs_update(self):
        """Test case for orgs_v1_orgs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
