# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assets_nodes_api import AssetsNodesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetsNodesApi(unittest.TestCase):
    """AssetsNodesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assets_nodes_api.AssetsNodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assets_v1_nodes_assets_add_partial_update(self):
        """Test case for assets_v1_nodes_assets_add_partial_update

        """
        pass

    def test_assets_v1_nodes_assets_add_update(self):
        """Test case for assets_v1_nodes_assets_add_update

        """
        pass

    def test_assets_v1_nodes_assets_list(self):
        """Test case for assets_v1_nodes_assets_list

        """
        pass

    def test_assets_v1_nodes_assets_remove_partial_update(self):
        """Test case for assets_v1_nodes_assets_remove_partial_update

        """
        pass

    def test_assets_v1_nodes_assets_remove_update(self):
        """Test case for assets_v1_nodes_assets_remove_update

        """
        pass

    def test_assets_v1_nodes_assets_replace_partial_update(self):
        """Test case for assets_v1_nodes_assets_replace_partial_update

        """
        pass

    def test_assets_v1_nodes_assets_replace_update(self):
        """Test case for assets_v1_nodes_assets_replace_update

        """
        pass

    def test_assets_v1_nodes_children_add_partial_update(self):
        """Test case for assets_v1_nodes_children_add_partial_update

        """
        pass

    def test_assets_v1_nodes_children_add_update(self):
        """Test case for assets_v1_nodes_children_add_update

        """
        pass

    def test_assets_v1_nodes_children_create(self):
        """Test case for assets_v1_nodes_children_create

        """
        pass

    def test_assets_v1_nodes_children_create_0(self):
        """Test case for assets_v1_nodes_children_create_0

        """
        pass

    def test_assets_v1_nodes_children_list(self):
        """Test case for assets_v1_nodes_children_list

        """
        pass

    def test_assets_v1_nodes_children_list_0(self):
        """Test case for assets_v1_nodes_children_list_0

        """
        pass

    def test_assets_v1_nodes_children_tree_list(self):
        """Test case for assets_v1_nodes_children_tree_list

        """
        pass

    def test_assets_v1_nodes_create(self):
        """Test case for assets_v1_nodes_create

        """
        pass

    def test_assets_v1_nodes_delete(self):
        """Test case for assets_v1_nodes_delete

        """
        pass

    def test_assets_v1_nodes_list(self):
        """Test case for assets_v1_nodes_list

        """
        pass

    def test_assets_v1_nodes_partial_update(self):
        """Test case for assets_v1_nodes_partial_update

        """
        pass

    def test_assets_v1_nodes_read(self):
        """Test case for assets_v1_nodes_read

        """
        pass

    def test_assets_v1_nodes_refresh_assets_amount_list(self):
        """Test case for assets_v1_nodes_refresh_assets_amount_list

        """
        pass

    def test_assets_v1_nodes_refresh_hardware_info_list(self):
        """Test case for assets_v1_nodes_refresh_hardware_info_list

        """
        pass

    def test_assets_v1_nodes_test_connective_list(self):
        """Test case for assets_v1_nodes_test_connective_list

        """
        pass

    def test_assets_v1_nodes_tree_list(self):
        """Test case for assets_v1_nodes_tree_list

        """
        pass

    def test_assets_v1_nodes_update(self):
        """Test case for assets_v1_nodes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
