# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.common_resources_api import CommonResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommonResourcesApi(unittest.TestCase):
    """CommonResourcesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.common_resources_api.CommonResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_common_v1_resources_cache_create(self):
        """Test case for common_v1_resources_cache_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
