# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.xpack_change_auth_plan_api import XpackChangeAuthPlanApi  # noqa: E501
from swagger_client.rest import ApiException


class TestXpackChangeAuthPlanApi(unittest.TestCase):
    """XpackChangeAuthPlanApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.xpack_change_auth_plan_api.XpackChangeAuthPlanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_add_partial_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_add_partial_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_add_read(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_add_read

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_add_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_add_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_remove_partial_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_remove_partial_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_remove_read(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_remove_read

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_asset_remove_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_asset_remove_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_create(self):
        """Test case for xpack_v1_change_auth_plan_plan_create

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_delete(self):
        """Test case for xpack_v1_change_auth_plan_plan_delete

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_delete_0(self):
        """Test case for xpack_v1_change_auth_plan_plan_delete_0

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_execution_create(self):
        """Test case for xpack_v1_change_auth_plan_plan_execution_create

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_execution_list(self):
        """Test case for xpack_v1_change_auth_plan_plan_execution_list

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_execution_subtask_list(self):
        """Test case for xpack_v1_change_auth_plan_plan_execution_subtask_list

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_execution_subtask_partial_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_execution_subtask_partial_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_execution_subtask_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_execution_subtask_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_list(self):
        """Test case for xpack_v1_change_auth_plan_plan_list

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_partial_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_partial_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_partial_update_0(self):
        """Test case for xpack_v1_change_auth_plan_plan_partial_update_0

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_read(self):
        """Test case for xpack_v1_change_auth_plan_plan_read

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_update(self):
        """Test case for xpack_v1_change_auth_plan_plan_update

        """
        pass

    def test_xpack_v1_change_auth_plan_plan_update_0(self):
        """Test case for xpack_v1_change_auth_plan_plan_update_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
