# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assets_admin_users_api import AssetsAdminUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetsAdminUsersApi(unittest.TestCase):
    """AssetsAdminUsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assets_admin_users_api.AssetsAdminUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assets_v1_admin_users_assets_list(self):
        """Test case for assets_v1_admin_users_assets_list

        """
        pass

    def test_assets_v1_admin_users_auth_partial_update(self):
        """Test case for assets_v1_admin_users_auth_partial_update

        """
        pass

    def test_assets_v1_admin_users_auth_update(self):
        """Test case for assets_v1_admin_users_auth_update

        """
        pass

    def test_assets_v1_admin_users_connective_read(self):
        """Test case for assets_v1_admin_users_connective_read

        """
        pass

    def test_assets_v1_admin_users_create(self):
        """Test case for assets_v1_admin_users_create

        """
        pass

    def test_assets_v1_admin_users_delete(self):
        """Test case for assets_v1_admin_users_delete

        """
        pass

    def test_assets_v1_admin_users_delete_0(self):
        """Test case for assets_v1_admin_users_delete_0

        """
        pass

    def test_assets_v1_admin_users_list(self):
        """Test case for assets_v1_admin_users_list

        """
        pass

    def test_assets_v1_admin_users_nodes_partial_update(self):
        """Test case for assets_v1_admin_users_nodes_partial_update

        """
        pass

    def test_assets_v1_admin_users_nodes_update(self):
        """Test case for assets_v1_admin_users_nodes_update

        """
        pass

    def test_assets_v1_admin_users_partial_update(self):
        """Test case for assets_v1_admin_users_partial_update

        """
        pass

    def test_assets_v1_admin_users_partial_update_0(self):
        """Test case for assets_v1_admin_users_partial_update_0

        """
        pass

    def test_assets_v1_admin_users_read(self):
        """Test case for assets_v1_admin_users_read

        """
        pass

    def test_assets_v1_admin_users_update(self):
        """Test case for assets_v1_admin_users_update

        """
        pass

    def test_assets_v1_admin_users_update_0(self):
        """Test case for assets_v1_admin_users_update_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
