# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.terminal_commands_api import TerminalCommandsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTerminalCommandsApi(unittest.TestCase):
    """TerminalCommandsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.terminal_commands_api.TerminalCommandsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_terminal_v1_commands_export_list(self):
        """Test case for terminal_v1_commands_export_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
