# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.perms_asset_permissions_api import PermsAssetPermissionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPermsAssetPermissionsApi(unittest.TestCase):
    """PermsAssetPermissionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.perms_asset_permissions_api.PermsAssetPermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_perms_v1_asset_permissions_asset_add_partial_update(self):
        """Test case for perms_v1_asset_permissions_asset_add_partial_update

        """
        pass

    def test_perms_v1_asset_permissions_asset_add_read(self):
        """Test case for perms_v1_asset_permissions_asset_add_read

        """
        pass

    def test_perms_v1_asset_permissions_asset_add_update(self):
        """Test case for perms_v1_asset_permissions_asset_add_update

        """
        pass

    def test_perms_v1_asset_permissions_asset_remove_partial_update(self):
        """Test case for perms_v1_asset_permissions_asset_remove_partial_update

        """
        pass

    def test_perms_v1_asset_permissions_asset_remove_read(self):
        """Test case for perms_v1_asset_permissions_asset_remove_read

        """
        pass

    def test_perms_v1_asset_permissions_asset_remove_update(self):
        """Test case for perms_v1_asset_permissions_asset_remove_update

        """
        pass

    def test_perms_v1_asset_permissions_assets_list(self):
        """Test case for perms_v1_asset_permissions_assets_list

        """
        pass

    def test_perms_v1_asset_permissions_create(self):
        """Test case for perms_v1_asset_permissions_create

        """
        pass

    def test_perms_v1_asset_permissions_delete(self):
        """Test case for perms_v1_asset_permissions_delete

        """
        pass

    def test_perms_v1_asset_permissions_list(self):
        """Test case for perms_v1_asset_permissions_list

        """
        pass

    def test_perms_v1_asset_permissions_partial_update(self):
        """Test case for perms_v1_asset_permissions_partial_update

        """
        pass

    def test_perms_v1_asset_permissions_read(self):
        """Test case for perms_v1_asset_permissions_read

        """
        pass

    def test_perms_v1_asset_permissions_update(self):
        """Test case for perms_v1_asset_permissions_update

        """
        pass

    def test_perms_v1_asset_permissions_user_actions_read(self):
        """Test case for perms_v1_asset_permissions_user_actions_read

        """
        pass

    def test_perms_v1_asset_permissions_user_add_partial_update(self):
        """Test case for perms_v1_asset_permissions_user_add_partial_update

        """
        pass

    def test_perms_v1_asset_permissions_user_add_read(self):
        """Test case for perms_v1_asset_permissions_user_add_read

        """
        pass

    def test_perms_v1_asset_permissions_user_add_update(self):
        """Test case for perms_v1_asset_permissions_user_add_update

        """
        pass

    def test_perms_v1_asset_permissions_user_remove_partial_update(self):
        """Test case for perms_v1_asset_permissions_user_remove_partial_update

        """
        pass

    def test_perms_v1_asset_permissions_user_remove_read(self):
        """Test case for perms_v1_asset_permissions_user_remove_read

        """
        pass

    def test_perms_v1_asset_permissions_user_remove_update(self):
        """Test case for perms_v1_asset_permissions_user_remove_update

        """
        pass

    def test_perms_v1_asset_permissions_user_validate_list(self):
        """Test case for perms_v1_asset_permissions_user_validate_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
