# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.plan_execution_subtask import PlanExecutionSubtask  # noqa: E501
from swagger_client.rest import ApiException


class TestPlanExecutionSubtask(unittest.TestCase):
    """PlanExecutionSubtask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanExecutionSubtask(self):
        """Test PlanExecutionSubtask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.plan_execution_subtask.PlanExecutionSubtask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
