# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_users_api import UsersUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersUsersApi(unittest.TestCase):
    """UsersUsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.users_users_api.UsersUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_v1_users_create(self):
        """Test case for users_v1_users_create

        """
        pass

    def test_users_v1_users_delete(self):
        """Test case for users_v1_users_delete

        """
        pass

    def test_users_v1_users_delete_0(self):
        """Test case for users_v1_users_delete_0

        """
        pass

    def test_users_v1_users_groups_partial_update(self):
        """Test case for users_v1_users_groups_partial_update

        """
        pass

    def test_users_v1_users_groups_read(self):
        """Test case for users_v1_users_groups_read

        """
        pass

    def test_users_v1_users_groups_update(self):
        """Test case for users_v1_users_groups_update

        """
        pass

    def test_users_v1_users_list(self):
        """Test case for users_v1_users_list

        """
        pass

    def test_users_v1_users_otp_reset_read(self):
        """Test case for users_v1_users_otp_reset_read

        """
        pass

    def test_users_v1_users_partial_update(self):
        """Test case for users_v1_users_partial_update

        """
        pass

    def test_users_v1_users_partial_update_0(self):
        """Test case for users_v1_users_partial_update_0

        """
        pass

    def test_users_v1_users_password_partial_update(self):
        """Test case for users_v1_users_password_partial_update

        """
        pass

    def test_users_v1_users_password_read(self):
        """Test case for users_v1_users_password_read

        """
        pass

    def test_users_v1_users_password_reset_partial_update(self):
        """Test case for users_v1_users_password_reset_partial_update

        """
        pass

    def test_users_v1_users_password_reset_update(self):
        """Test case for users_v1_users_password_reset_update

        """
        pass

    def test_users_v1_users_password_update(self):
        """Test case for users_v1_users_password_update

        """
        pass

    def test_users_v1_users_pubkey_reset_partial_update(self):
        """Test case for users_v1_users_pubkey_reset_partial_update

        """
        pass

    def test_users_v1_users_pubkey_reset_update(self):
        """Test case for users_v1_users_pubkey_reset_update

        """
        pass

    def test_users_v1_users_pubkey_update_partial_update(self):
        """Test case for users_v1_users_pubkey_update_partial_update

        """
        pass

    def test_users_v1_users_pubkey_update_update(self):
        """Test case for users_v1_users_pubkey_update_update

        """
        pass

    def test_users_v1_users_read(self):
        """Test case for users_v1_users_read

        """
        pass

    def test_users_v1_users_unblock_partial_update(self):
        """Test case for users_v1_users_unblock_partial_update

        """
        pass

    def test_users_v1_users_unblock_update(self):
        """Test case for users_v1_users_unblock_update

        """
        pass

    def test_users_v1_users_update(self):
        """Test case for users_v1_users_update

        """
        pass

    def test_users_v1_users_update_0(self):
        """Test case for users_v1_users_update_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
