# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.terminal_command_api import TerminalCommandApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTerminalCommandApi(unittest.TestCase):
    """TerminalCommandApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.terminal_command_api.TerminalCommandApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_terminal_v1_command_create(self):
        """Test case for terminal_v1_command_create

        """
        pass

    def test_terminal_v1_command_delete(self):
        """Test case for terminal_v1_command_delete

        """
        pass

    def test_terminal_v1_command_list(self):
        """Test case for terminal_v1_command_list

        """
        pass

    def test_terminal_v1_command_partial_update(self):
        """Test case for terminal_v1_command_partial_update

        """
        pass

    def test_terminal_v1_command_read(self):
        """Test case for terminal_v1_command_read

        """
        pass

    def test_terminal_v1_command_update(self):
        """Test case for terminal_v1_command_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
