# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.xpack_cloud_api import XpackCloudApi  # noqa: E501
from swagger_client.rest import ApiException


class TestXpackCloudApi(unittest.TestCase):
    """XpackCloudApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.xpack_cloud_api.XpackCloudApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_xpack_v1_cloud_account_create(self):
        """Test case for xpack_v1_cloud_account_create

        """
        pass

    def test_xpack_v1_cloud_account_delete(self):
        """Test case for xpack_v1_cloud_account_delete

        """
        pass

    def test_xpack_v1_cloud_account_delete_0(self):
        """Test case for xpack_v1_cloud_account_delete_0

        """
        pass

    def test_xpack_v1_cloud_account_list(self):
        """Test case for xpack_v1_cloud_account_list

        """
        pass

    def test_xpack_v1_cloud_account_partial_update(self):
        """Test case for xpack_v1_cloud_account_partial_update

        """
        pass

    def test_xpack_v1_cloud_account_partial_update_0(self):
        """Test case for xpack_v1_cloud_account_partial_update_0

        """
        pass

    def test_xpack_v1_cloud_account_read(self):
        """Test case for xpack_v1_cloud_account_read

        """
        pass

    def test_xpack_v1_cloud_account_update(self):
        """Test case for xpack_v1_cloud_account_update

        """
        pass

    def test_xpack_v1_cloud_account_update_0(self):
        """Test case for xpack_v1_cloud_account_update_0

        """
        pass

    def test_xpack_v1_cloud_get_instances_list(self):
        """Test case for xpack_v1_cloud_get_instances_list

        """
        pass

    def test_xpack_v1_cloud_get_regions_list(self):
        """Test case for xpack_v1_cloud_get_regions_list

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_create(self):
        """Test case for xpack_v1_cloud_sync_instance_task_create

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_delete(self):
        """Test case for xpack_v1_cloud_sync_instance_task_delete

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_delete_0(self):
        """Test case for xpack_v1_cloud_sync_instance_task_delete_0

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_list(self):
        """Test case for xpack_v1_cloud_sync_instance_task_list

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_partial_update(self):
        """Test case for xpack_v1_cloud_sync_instance_task_partial_update

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_partial_update_0(self):
        """Test case for xpack_v1_cloud_sync_instance_task_partial_update_0

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_read(self):
        """Test case for xpack_v1_cloud_sync_instance_task_read

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_run_list(self):
        """Test case for xpack_v1_cloud_sync_instance_task_run_list

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_update(self):
        """Test case for xpack_v1_cloud_sync_instance_task_update

        """
        pass

    def test_xpack_v1_cloud_sync_instance_task_update_0(self):
        """Test case for xpack_v1_cloud_sync_instance_task_update_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
