# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.settings_ldap_api import SettingsLdapApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingsLdapApi(unittest.TestCase):
    """SettingsLdapApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.settings_ldap_api.SettingsLdapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settings_v1_ldap_testing_create(self):
        """Test case for settings_v1_ldap_testing_create

        """
        pass

    def test_settings_v1_ldap_users_list(self):
        """Test case for settings_v1_ldap_users_list

        """
        pass

    def test_settings_v1_ldap_users_sync_create(self):
        """Test case for settings_v1_ldap_users_sync_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
