# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assets_asset_users_api import AssetsAssetUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetsAssetUsersApi(unittest.TestCase):
    """AssetsAssetUsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assets_asset_users_api.AssetsAssetUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assets_v1_asset_users_auth_info_read(self):
        """Test case for assets_v1_asset_users_auth_info_read

        """
        pass

    def test_assets_v1_asset_users_create(self):
        """Test case for assets_v1_asset_users_create

        """
        pass

    def test_assets_v1_asset_users_list(self):
        """Test case for assets_v1_asset_users_list

        """
        pass

    def test_assets_v1_asset_users_read(self):
        """Test case for assets_v1_asset_users_read

        """
        pass

    def test_assets_v1_asset_users_test_connective_read(self):
        """Test case for assets_v1_asset_users_test_connective_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
