# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.assets_domains_api import AssetsDomainsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetsDomainsApi(unittest.TestCase):
    """AssetsDomainsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.assets_domains_api.AssetsDomainsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assets_v1_domains_create(self):
        """Test case for assets_v1_domains_create

        """
        pass

    def test_assets_v1_domains_delete(self):
        """Test case for assets_v1_domains_delete

        """
        pass

    def test_assets_v1_domains_delete_0(self):
        """Test case for assets_v1_domains_delete_0

        """
        pass

    def test_assets_v1_domains_list(self):
        """Test case for assets_v1_domains_list

        """
        pass

    def test_assets_v1_domains_partial_update(self):
        """Test case for assets_v1_domains_partial_update

        """
        pass

    def test_assets_v1_domains_partial_update_0(self):
        """Test case for assets_v1_domains_partial_update_0

        """
        pass

    def test_assets_v1_domains_read(self):
        """Test case for assets_v1_domains_read

        """
        pass

    def test_assets_v1_domains_update(self):
        """Test case for assets_v1_domains_update

        """
        pass

    def test_assets_v1_domains_update_0(self):
        """Test case for assets_v1_domains_update_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
