# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ops_adhoc_api import OpsAdhocApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOpsAdhocApi(unittest.TestCase):
    """OpsAdhocApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.ops_adhoc_api.OpsAdhocApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ops_v1_adhoc_create(self):
        """Test case for ops_v1_adhoc_create

        """
        pass

    def test_ops_v1_adhoc_delete(self):
        """Test case for ops_v1_adhoc_delete

        """
        pass

    def test_ops_v1_adhoc_list(self):
        """Test case for ops_v1_adhoc_list

        """
        pass

    def test_ops_v1_adhoc_partial_update(self):
        """Test case for ops_v1_adhoc_partial_update

        """
        pass

    def test_ops_v1_adhoc_read(self):
        """Test case for ops_v1_adhoc_read

        """
        pass

    def test_ops_v1_adhoc_update(self):
        """Test case for ops_v1_adhoc_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
