# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AdminUserAuth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password': 'str',
        'private_key': 'str'
    }

    attribute_map = {
        'password': 'password',
        'private_key': 'private_key'
    }

    def __init__(self, password=None, private_key=None):  # noqa: E501
        """AdminUserAuth - a model defined in Swagger"""  # noqa: E501

        self._password = None
        self._private_key = None
        self.discriminator = None

        if password is not None:
            self.password = password
        if private_key is not None:
            self.private_key = private_key

    @property
    def password(self):
        """Gets the password of this AdminUserAuth.  # noqa: E501


        :return: The password of this AdminUserAuth.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AdminUserAuth.


        :param password: The password of this AdminUserAuth.  # noqa: E501
        :type: str
        """
        if password is not None and len(password) > 1024:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `1024`")  # noqa: E501

        self._password = password

    @property
    def private_key(self):
        """Gets the private_key of this AdminUserAuth.  # noqa: E501


        :return: The private_key of this AdminUserAuth.  # noqa: E501
        :rtype: str
        """
        return self._private_key

    @private_key.setter
    def private_key(self, private_key):
        """Sets the private_key of this AdminUserAuth.


        :param private_key: The private_key of this AdminUserAuth.  # noqa: E501
        :type: str
        """
        if private_key is not None and len(private_key) > 4096:
            raise ValueError("Invalid value for `private_key`, length must be less than or equal to `4096`")  # noqa: E501

        self._private_key = private_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminUserAuth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
