# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AssetPermissionCreateUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'org_id': 'str',
        'org_name': 'str',
        'actions': 'list[int]',
        'name': 'str',
        'is_active': 'bool',
        'date_start': 'datetime',
        'date_expired': 'datetime',
        'comment': 'str',
        'users': 'list[str]',
        'user_groups': 'list[str]',
        'assets': 'list[str]',
        'nodes': 'list[str]',
        'system_users': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'org_id': 'org_id',
        'org_name': 'org_name',
        'actions': 'actions',
        'name': 'name',
        'is_active': 'is_active',
        'date_start': 'date_start',
        'date_expired': 'date_expired',
        'comment': 'comment',
        'users': 'users',
        'user_groups': 'user_groups',
        'assets': 'assets',
        'nodes': 'nodes',
        'system_users': 'system_users'
    }

    def __init__(self, id=None, org_id='', org_name=None, actions=None, name=None, is_active=None, date_start=None, date_expired=None, comment=None, users=None, user_groups=None, assets=None, nodes=None, system_users=None):  # noqa: E501
        """AssetPermissionCreateUpdate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._org_id = None
        self._org_name = None
        self._actions = None
        self._name = None
        self._is_active = None
        self._date_start = None
        self._date_expired = None
        self._comment = None
        self._users = None
        self._user_groups = None
        self._assets = None
        self._nodes = None
        self._system_users = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if org_id is not None:
            self.org_id = org_id
        if org_name is not None:
            self.org_name = org_name
        if actions is not None:
            self.actions = actions
        self.name = name
        if is_active is not None:
            self.is_active = is_active
        if date_start is not None:
            self.date_start = date_start
        if date_expired is not None:
            self.date_expired = date_expired
        if comment is not None:
            self.comment = comment
        if users is not None:
            self.users = users
        if user_groups is not None:
            self.user_groups = user_groups
        if assets is not None:
            self.assets = assets
        if nodes is not None:
            self.nodes = nodes
        self.system_users = system_users

    @property
    def id(self):
        """Gets the id of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The id of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssetPermissionCreateUpdate.


        :param id: The id of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def org_id(self):
        """Gets the org_id of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The org_id of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this AssetPermissionCreateUpdate.


        :param org_id: The org_id of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def org_name(self):
        """Gets the org_name of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The org_name of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this AssetPermissionCreateUpdate.


        :param org_name: The org_name of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    @property
    def actions(self):
        """Gets the actions of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The actions of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[int]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this AssetPermissionCreateUpdate.


        :param actions: The actions of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[int]
        """

        self._actions = actions

    @property
    def name(self):
        """Gets the name of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The name of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AssetPermissionCreateUpdate.


        :param name: The name of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 128:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def is_active(self):
        """Gets the is_active of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The is_active of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this AssetPermissionCreateUpdate.


        :param is_active: The is_active of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def date_start(self):
        """Gets the date_start of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The date_start of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: datetime
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this AssetPermissionCreateUpdate.


        :param date_start: The date_start of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: datetime
        """

        self._date_start = date_start

    @property
    def date_expired(self):
        """Gets the date_expired of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The date_expired of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: datetime
        """
        return self._date_expired

    @date_expired.setter
    def date_expired(self, date_expired):
        """Sets the date_expired of this AssetPermissionCreateUpdate.


        :param date_expired: The date_expired of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: datetime
        """

        self._date_expired = date_expired

    @property
    def comment(self):
        """Gets the comment of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The comment of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this AssetPermissionCreateUpdate.


        :param comment: The comment of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def users(self):
        """Gets the users of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The users of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this AssetPermissionCreateUpdate.


        :param users: The users of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    @property
    def user_groups(self):
        """Gets the user_groups of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The user_groups of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_groups

    @user_groups.setter
    def user_groups(self, user_groups):
        """Sets the user_groups of this AssetPermissionCreateUpdate.


        :param user_groups: The user_groups of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[str]
        """

        self._user_groups = user_groups

    @property
    def assets(self):
        """Gets the assets of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The assets of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this AssetPermissionCreateUpdate.


        :param assets: The assets of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[str]
        """

        self._assets = assets

    @property
    def nodes(self):
        """Gets the nodes of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The nodes of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this AssetPermissionCreateUpdate.


        :param nodes: The nodes of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[str]
        """

        self._nodes = nodes

    @property
    def system_users(self):
        """Gets the system_users of this AssetPermissionCreateUpdate.  # noqa: E501


        :return: The system_users of this AssetPermissionCreateUpdate.  # noqa: E501
        :rtype: list[str]
        """
        return self._system_users

    @system_users.setter
    def system_users(self, system_users):
        """Sets the system_users of this AssetPermissionCreateUpdate.


        :param system_users: The system_users of this AssetPermissionCreateUpdate.  # noqa: E501
        :type: list[str]
        """
        if system_users is None:
            raise ValueError("Invalid value for `system_users`, must not be `None`")  # noqa: E501

        self._system_users = system_users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetPermissionCreateUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
