# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Label(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'value': 'str',
        'category': 'str',
        'is_active': 'bool',
        'comment': 'str',
        'date_created': 'datetime',
        'asset_count': 'str',
        'assets': 'list[str]',
        'get_category_display': 'str',
        'org_id': 'str',
        'org_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'value': 'value',
        'category': 'category',
        'is_active': 'is_active',
        'comment': 'comment',
        'date_created': 'date_created',
        'asset_count': 'asset_count',
        'assets': 'assets',
        'get_category_display': 'get_category_display',
        'org_id': 'org_id',
        'org_name': 'org_name'
    }

    def __init__(self, id=None, name=None, value=None, category=None, is_active=None, comment=None, date_created=None, asset_count=None, assets=None, get_category_display=None, org_id='', org_name=None):  # noqa: E501
        """Label - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._value = None
        self._category = None
        self._is_active = None
        self._comment = None
        self._date_created = None
        self._asset_count = None
        self._assets = None
        self._get_category_display = None
        self._org_id = None
        self._org_name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.value = value
        if category is not None:
            self.category = category
        if is_active is not None:
            self.is_active = is_active
        if comment is not None:
            self.comment = comment
        if date_created is not None:
            self.date_created = date_created
        if asset_count is not None:
            self.asset_count = asset_count
        self.assets = assets
        if get_category_display is not None:
            self.get_category_display = get_category_display
        if org_id is not None:
            self.org_id = org_id
        if org_name is not None:
            self.org_name = org_name

    @property
    def id(self):
        """Gets the id of this Label.  # noqa: E501


        :return: The id of this Label.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Label.


        :param id: The id of this Label.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Label.  # noqa: E501


        :return: The name of this Label.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Label.


        :param name: The name of this Label.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 128:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this Label.  # noqa: E501


        :return: The value of this Label.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Label.


        :param value: The value of this Label.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        if value is not None and len(value) > 128:
            raise ValueError("Invalid value for `value`, length must be less than or equal to `128`")  # noqa: E501
        if value is not None and len(value) < 1:
            raise ValueError("Invalid value for `value`, length must be greater than or equal to `1`")  # noqa: E501

        self._value = value

    @property
    def category(self):
        """Gets the category of this Label.  # noqa: E501


        :return: The category of this Label.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Label.


        :param category: The category of this Label.  # noqa: E501
        :type: str
        """
        allowed_values = ["S", "U"]  # noqa: E501
        if category not in allowed_values:
            raise ValueError(
                "Invalid value for `category` ({0}), must be one of {1}"  # noqa: E501
                .format(category, allowed_values)
            )

        self._category = category

    @property
    def is_active(self):
        """Gets the is_active of this Label.  # noqa: E501


        :return: The is_active of this Label.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this Label.


        :param is_active: The is_active of this Label.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def comment(self):
        """Gets the comment of this Label.  # noqa: E501


        :return: The comment of this Label.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Label.


        :param comment: The comment of this Label.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def date_created(self):
        """Gets the date_created of this Label.  # noqa: E501


        :return: The date_created of this Label.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this Label.


        :param date_created: The date_created of this Label.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def asset_count(self):
        """Gets the asset_count of this Label.  # noqa: E501


        :return: The asset_count of this Label.  # noqa: E501
        :rtype: str
        """
        return self._asset_count

    @asset_count.setter
    def asset_count(self, asset_count):
        """Sets the asset_count of this Label.


        :param asset_count: The asset_count of this Label.  # noqa: E501
        :type: str
        """

        self._asset_count = asset_count

    @property
    def assets(self):
        """Gets the assets of this Label.  # noqa: E501


        :return: The assets of this Label.  # noqa: E501
        :rtype: list[str]
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this Label.


        :param assets: The assets of this Label.  # noqa: E501
        :type: list[str]
        """
        if assets is None:
            raise ValueError("Invalid value for `assets`, must not be `None`")  # noqa: E501

        self._assets = assets

    @property
    def get_category_display(self):
        """Gets the get_category_display of this Label.  # noqa: E501


        :return: The get_category_display of this Label.  # noqa: E501
        :rtype: str
        """
        return self._get_category_display

    @get_category_display.setter
    def get_category_display(self, get_category_display):
        """Sets the get_category_display of this Label.


        :param get_category_display: The get_category_display of this Label.  # noqa: E501
        :type: str
        """

        self._get_category_display = get_category_display

    @property
    def org_id(self):
        """Gets the org_id of this Label.  # noqa: E501


        :return: The org_id of this Label.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Label.


        :param org_id: The org_id of this Label.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def org_name(self):
        """Gets the org_name of this Label.  # noqa: E501


        :return: The org_name of this Label.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this Label.


        :param org_name: The org_name of this Label.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Label):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
