# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RemoteAppPermission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'users': 'list[str]',
        'user_groups': 'list[str]',
        'remote_apps': 'list[str]',
        'comment': 'str',
        'is_active': 'bool',
        'date_start': 'datetime',
        'date_expired': 'datetime',
        'is_valid': 'str',
        'created_by': 'str',
        'date_created': 'datetime',
        'org_id': 'str',
        'org_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'users': 'users',
        'user_groups': 'user_groups',
        'remote_apps': 'remote_apps',
        'comment': 'comment',
        'is_active': 'is_active',
        'date_start': 'date_start',
        'date_expired': 'date_expired',
        'is_valid': 'is_valid',
        'created_by': 'created_by',
        'date_created': 'date_created',
        'org_id': 'org_id',
        'org_name': 'org_name'
    }

    def __init__(self, id=None, name=None, users=None, user_groups=None, remote_apps=None, comment=None, is_active=None, date_start=None, date_expired=None, is_valid=None, created_by=None, date_created=None, org_id='', org_name=None):  # noqa: E501
        """RemoteAppPermission - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._users = None
        self._user_groups = None
        self._remote_apps = None
        self._comment = None
        self._is_active = None
        self._date_start = None
        self._date_expired = None
        self._is_valid = None
        self._created_by = None
        self._date_created = None
        self._org_id = None
        self._org_name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if users is not None:
            self.users = users
        if user_groups is not None:
            self.user_groups = user_groups
        if remote_apps is not None:
            self.remote_apps = remote_apps
        if comment is not None:
            self.comment = comment
        if is_active is not None:
            self.is_active = is_active
        if date_start is not None:
            self.date_start = date_start
        if date_expired is not None:
            self.date_expired = date_expired
        if is_valid is not None:
            self.is_valid = is_valid
        if created_by is not None:
            self.created_by = created_by
        if date_created is not None:
            self.date_created = date_created
        if org_id is not None:
            self.org_id = org_id
        if org_name is not None:
            self.org_name = org_name

    @property
    def id(self):
        """Gets the id of this RemoteAppPermission.  # noqa: E501


        :return: The id of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RemoteAppPermission.


        :param id: The id of this RemoteAppPermission.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this RemoteAppPermission.  # noqa: E501


        :return: The name of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RemoteAppPermission.


        :param name: The name of this RemoteAppPermission.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 128:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `128`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def users(self):
        """Gets the users of this RemoteAppPermission.  # noqa: E501


        :return: The users of this RemoteAppPermission.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this RemoteAppPermission.


        :param users: The users of this RemoteAppPermission.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    @property
    def user_groups(self):
        """Gets the user_groups of this RemoteAppPermission.  # noqa: E501


        :return: The user_groups of this RemoteAppPermission.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_groups

    @user_groups.setter
    def user_groups(self, user_groups):
        """Sets the user_groups of this RemoteAppPermission.


        :param user_groups: The user_groups of this RemoteAppPermission.  # noqa: E501
        :type: list[str]
        """

        self._user_groups = user_groups

    @property
    def remote_apps(self):
        """Gets the remote_apps of this RemoteAppPermission.  # noqa: E501


        :return: The remote_apps of this RemoteAppPermission.  # noqa: E501
        :rtype: list[str]
        """
        return self._remote_apps

    @remote_apps.setter
    def remote_apps(self, remote_apps):
        """Sets the remote_apps of this RemoteAppPermission.


        :param remote_apps: The remote_apps of this RemoteAppPermission.  # noqa: E501
        :type: list[str]
        """

        self._remote_apps = remote_apps

    @property
    def comment(self):
        """Gets the comment of this RemoteAppPermission.  # noqa: E501


        :return: The comment of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this RemoteAppPermission.


        :param comment: The comment of this RemoteAppPermission.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def is_active(self):
        """Gets the is_active of this RemoteAppPermission.  # noqa: E501


        :return: The is_active of this RemoteAppPermission.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this RemoteAppPermission.


        :param is_active: The is_active of this RemoteAppPermission.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def date_start(self):
        """Gets the date_start of this RemoteAppPermission.  # noqa: E501


        :return: The date_start of this RemoteAppPermission.  # noqa: E501
        :rtype: datetime
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this RemoteAppPermission.


        :param date_start: The date_start of this RemoteAppPermission.  # noqa: E501
        :type: datetime
        """

        self._date_start = date_start

    @property
    def date_expired(self):
        """Gets the date_expired of this RemoteAppPermission.  # noqa: E501


        :return: The date_expired of this RemoteAppPermission.  # noqa: E501
        :rtype: datetime
        """
        return self._date_expired

    @date_expired.setter
    def date_expired(self, date_expired):
        """Sets the date_expired of this RemoteAppPermission.


        :param date_expired: The date_expired of this RemoteAppPermission.  # noqa: E501
        :type: datetime
        """

        self._date_expired = date_expired

    @property
    def is_valid(self):
        """Gets the is_valid of this RemoteAppPermission.  # noqa: E501


        :return: The is_valid of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._is_valid

    @is_valid.setter
    def is_valid(self, is_valid):
        """Sets the is_valid of this RemoteAppPermission.


        :param is_valid: The is_valid of this RemoteAppPermission.  # noqa: E501
        :type: str
        """

        self._is_valid = is_valid

    @property
    def created_by(self):
        """Gets the created_by of this RemoteAppPermission.  # noqa: E501


        :return: The created_by of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this RemoteAppPermission.


        :param created_by: The created_by of this RemoteAppPermission.  # noqa: E501
        :type: str
        """
        if created_by is not None and len(created_by) < 1:
            raise ValueError("Invalid value for `created_by`, length must be greater than or equal to `1`")  # noqa: E501

        self._created_by = created_by

    @property
    def date_created(self):
        """Gets the date_created of this RemoteAppPermission.  # noqa: E501


        :return: The date_created of this RemoteAppPermission.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this RemoteAppPermission.


        :param date_created: The date_created of this RemoteAppPermission.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def org_id(self):
        """Gets the org_id of this RemoteAppPermission.  # noqa: E501


        :return: The org_id of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this RemoteAppPermission.


        :param org_id: The org_id of this RemoteAppPermission.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def org_name(self):
        """Gets the org_name of this RemoteAppPermission.  # noqa: E501


        :return: The org_name of this RemoteAppPermission.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this RemoteAppPermission.


        :param org_name: The org_name of this RemoteAppPermission.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoteAppPermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
