# coding: utf-8

"""
    Jumpserver API Docs

    Jumpserver Restful api docs  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@fit2cloud.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TerminalCommandApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def terminal_v1_command_create(self, data, **kwargs):  # noqa: E501
        """terminal_v1_command_create  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_create(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_create_with_http_info(data, **kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_create_with_http_info(data, **kwargs)  # noqa: E501
            return data

    def terminal_v1_command_create_with_http_info(self, data, **kwargs):  # noqa: E501
        """terminal_v1_command_create  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_create_with_http_info(data, async=True)
        >>> result = thread.get()

        :param async bool
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `terminal_v1_command_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SessionCommand',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def terminal_v1_command_delete(self, id, **kwargs):  # noqa: E501
        """terminal_v1_command_delete  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_delete(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_delete_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_delete_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def terminal_v1_command_delete_with_http_info(self, id, **kwargs):  # noqa: E501
        """terminal_v1_command_delete  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_delete_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `terminal_v1_command_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/{id}/', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def terminal_v1_command_list(self, **kwargs):  # noqa: E501
        """terminal_v1_command_list  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str asset: 
        :param str system_user: 
        :param str user: 
        :param str session: 
        :param str search: A search term.
        :param str order: Which field to use when ordering the results.
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :return: InlineResponse20019
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def terminal_v1_command_list_with_http_info(self, **kwargs):  # noqa: E501
        """terminal_v1_command_list  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str asset: 
        :param str system_user: 
        :param str user: 
        :param str session: 
        :param str search: A search term.
        :param str order: Which field to use when ordering the results.
        :param int limit: Number of results to return per page.
        :param int offset: The initial index from which to return the results.
        :return: InlineResponse20019
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['asset', 'system_user', 'user', 'session', 'search', 'order', 'limit', 'offset']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'asset' in params:
            query_params.append(('asset', params['asset']))  # noqa: E501
        if 'system_user' in params:
            query_params.append(('system_user', params['system_user']))  # noqa: E501
        if 'user' in params:
            query_params.append(('user', params['user']))  # noqa: E501
        if 'session' in params:
            query_params.append(('session', params['session']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501
        if 'order' in params:
            query_params.append(('order', params['order']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20019',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def terminal_v1_command_partial_update(self, id, data, **kwargs):  # noqa: E501
        """terminal_v1_command_partial_update  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_partial_update(id, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_partial_update_with_http_info(id, data, **kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_partial_update_with_http_info(id, data, **kwargs)  # noqa: E501
            return data

    def terminal_v1_command_partial_update_with_http_info(self, id, data, **kwargs):  # noqa: E501
        """terminal_v1_command_partial_update  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_partial_update_with_http_info(id, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `terminal_v1_command_partial_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `terminal_v1_command_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/{id}/', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SessionCommand',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def terminal_v1_command_read(self, id, **kwargs):  # noqa: E501
        """terminal_v1_command_read  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_read(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_read_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_read_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def terminal_v1_command_read_with_http_info(self, id, **kwargs):  # noqa: E501
        """terminal_v1_command_read  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_read_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `terminal_v1_command_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SessionCommand',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def terminal_v1_command_update(self, id, data, **kwargs):  # noqa: E501
        """terminal_v1_command_update  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_update(id, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.terminal_v1_command_update_with_http_info(id, data, **kwargs)  # noqa: E501
        else:
            (data) = self.terminal_v1_command_update_with_http_info(id, data, **kwargs)  # noqa: E501
            return data

    def terminal_v1_command_update_with_http_info(self, id, data, **kwargs):  # noqa: E501
        """terminal_v1_command_update  # noqa: E501

        接受app发送来的command log, 格式如下 {     \"user\": \"admin\",     \"asset\": \"localhost\",     \"system_user\": \"web\",     \"session\": \"xxxxxx\",     \"input\": \"whoami\",     \"output\": \"d2hvbWFp\",  # base64.b64encode(s)     \"timestamp\": 1485238673.0 }  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.terminal_v1_command_update_with_http_info(id, data, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: (required)
        :param SessionCommand data: (required)
        :return: SessionCommand
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'data']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method terminal_v1_command_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `terminal_v1_command_update`")  # noqa: E501
        # verify the required parameter 'data' is set
        if ('data' not in params or
                params['data'] is None):
            raise ValueError("Missing the required parameter `data` when calling `terminal_v1_command_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'data' in params:
            body_params = params['data']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/csv', '*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer']  # noqa: E501

        return self.api_client.call_api(
            '/terminal/v1/command/{id}/', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SessionCommand',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
